version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-test
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.dokka:dokka-maven-plugin
    versions:
    - 1.4.20-dev-65
